//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IyteMenu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restaurants
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Star { get; set; }
        public Nullable<int> Comments { get; set; }
        public string Address { get; set; }
        public Nullable<bool> Delivery { get; set; }
        public Nullable<bool> IsPopular { get; set; }
        public Nullable<int> MinimumFoodCost { get; set; }
        public Nullable<bool> Sodexo { get; set; }
        public Nullable<bool> Nakit { get; set; }
        public Nullable<bool> Multinet { get; set; }
        public Nullable<bool> SetCard { get; set; }
        public Nullable<System.TimeSpan> OpeningTime { get; set; }
        public Nullable<System.TimeSpan> CloseTime { get; set; }
        public Nullable<bool> CreditCardBankCard { get; set; }
        public Nullable<bool> TicketRestaurantCard { get; set; }
    }
}
